config/routes.rb
PassionBox::Application.routes.draw do
  get "trade/index"

  root :to => "home#index"

  match 'users/apply_user' => 'users#change_role', :via => :post, :as => :change_to_user, :role => User::USER
  match 'users/apply_curator' => 'users#change_role', :via => :post, :as => :change_to_curator, :role => User::CURATOR
  match 'users/apply_admin' => 'users#change_role', :via => :post, :as => :change_to_admin, :role => User::ADMIN
  resources :users, :only => [ :show, :edit, :update ]

  match '/auth/:provider/callback' => 'sessions#create'
  match '/signin' => 'sessions#new', :as => :signin
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/auth/failure' => 'sessions#failure'
  
  resources :items
  resources :boxes do 
    member do
      get :gallery
      get :edit_info
    end
  end
  match 'boxes/my_boxes' => 'boxes#my_boxes', :via =>:get, :as => :my_boxes
  
  resources :categories
  resources :templates
  resources :trade

end

app/views/templates/_form.html.erb
<fieldset>
  <div class="clearfix">
    <%= f.label :category %>
    <div class="input">
      <%= select :template, :category_id, Category.order_by(:name).all.collect {|c| [c.name, c.id]} %>
    </div>
  </div>
  <div class="clearfix">
    <%= f.label :global_fields %>
    <div class="input">
      <%= f.text_field :global_fields, :value => @template.global_fields_to_s %>
    </div>
  </div>
  <div class="clearfix">
    <%= f.label :user_fields %>
    <div class="input">
      <%= f.text_field :user_fields, :value => @template.user_fields_to_s %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', :class => 'btn primary' %>
    <%= link_to 'Cancel', templates_path, :class => 'btn' %>
  </div>
</fieldset>

app/views/templates/edit.html.erb
<h2>Edit Template</h2>

<%= form_for @template do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
<% end %>

app/views/templates/index.html.erb
<h1>Template</h1>
<p><%= link_to 'Create new Template', new_template_path %></p>

<table class="zebra-striped">
  <thead>
    <tr>
      <th>User Name</th>
      <th>Category</th>
      <th>Global Fields</th>
      <th>User Fields</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
  <% @templates.each do |t| %>
    <tr>
      <td><%= t.user.name %></td>
      <td><%= t.category.name %></td>
      <td><%= t.global_fields.join(', ') %></td>
      <td><%= t.user_fields.join(', ') %></td>
      <td><%= link_to 'Edit', edit_template_path(t) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/templates/new.html.erb
<h2>New Template</h2>

<%= form_for @template do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
<% end %>