config/routes.rb
PassionBox::Application.routes.draw do
  get "trade/index"

  root :to => "home#index"

  match 'users/apply_user' => 'users#change_role', :via => :post, :as => :change_to_user, :role => User::USER
  match 'users/apply_curator' => 'users#change_role', :via => :post, :as => :change_to_curator, :role => User::CURATOR
  match 'users/apply_admin' => 'users#change_role', :via => :post, :as => :change_to_admin, :role => User::ADMIN
  resources :users, :only => [ :show, :edit, :update ]

  match '/auth/:provider/callback' => 'sessions#create'
  match '/signin' => 'sessions#new', :as => :signin
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/auth/failure' => 'sessions#failure'
  
  resources :items
  resources :boxes do 
    member do
      get :gallery
      get :edit_info
    end
  end
  match 'boxes/my_boxes' => 'boxes#my_boxes', :via =>:get, :as => :my_boxes
  
  resources :categories
  resources :templates
  resources :trade

end

app/models/box.rb
class Box
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :name, :type => String
  field :category, :type => String
  
  belongs_to  :category
  belongs_to  :user
  has_many    :user_items
  
  validates_presence_of :name
end

app/controllers/box_controller.rb
class BoxController < ApplicationController
  def index
    @boxes = current_user.box
  end

  def new
    @box = Box.new
  end

  def create
    @box = current_user.boxes.new(params[:box])
    if @box.save
      redirect_to user_path(current_user), :notice => "Successfully created collection."
    else
      render :new
    end
  end

  def show
    @box = current_user.boxes.where(:_id => params[:id]).first
    @box_items = @box.user_items unless @box.nil?
  end
  
  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  def index
    @boxes = current_user.boxes
  end
  
  def my_boxes

  end
  
  def new
    @box = Box.new
    @box.category = Category.find(params[:category_id])
  end

  def create
    @box = current_user.boxes.new(params[:box])
    if @box.save
      flash[:success] = 'Collection created yeah!'
      # redirect_to my_boxes_path
      redirect_to @box
    else
      render :new
    end
  end

  def show
    @box = Box.find(params[:id])
  end
  
  def edit
    @box = Box.find(params[:id])
    @box_items = @box.user_items
  end
  
  def edit_info
    @box = Box.find(params[:id])
    @box_items = @box.user_items unless @box.nil?
  end

  def update
    @box = Box.find(params[:id])
    if @box.update_attributes(params[:box])
      flash[:success] = 'Awesome update!'
      redirect_to box_path(@box)
    else
      render :edit
    end
  end
 
  def destroy
  end

  def gallery
    @box = Box.find(params[:id])
    @template = @box.category.template
    respond_to do |r|
      r.xml
    end
  end

end

app/helpers/box_helper.rb
module BoxHelper
end

app/views/boxes/_form.html.erb
<%= form_for @box do |f| %>
<fieldset>
  <div class="clearfix">
    <%= f.label :category %>
    <div class="input">
      <%= select :box, :category_id, Category.order_by(:name).all.collect {|c| [c.name, c.id]} %>
    </div>
  </div>
  <div class="clearfix">
    <%= f.label :name %>
    <div class="input">
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', :class => 'btn primary' %>
    <%= link_to 'Cancel', boxes_path, :class => 'btn' %>
  </div>
</fieldset>
<% end %>

app/views/boxes/edit.html.erb
<div class="container">
  <div class="content">
    <div class="page-header">
      <% if current_user == @box.user_id %>
      <div class="quick-actions">
        <%= link_to 'Edit', edit_info_box_path(@box), :class => 'btn' %>
        <%= link_to 'Add Item', new_item_path(:id => @box.id), :class => 'btn info' %>
      </div>
      <% end %>
      <h1>Editing <%= @box.name %></h1>
    </div>
    <div class="row">
      <p>Category : <%= @box.category.name unless @box.category.nil? %></p>
      
      <% unless @box_items.blank? %>
        <table class="zebra-striped">
          <thead>
            <tr>
              <th>Title</th>
              <th>Tags</th>
              <th>&nbsp;</th>
            </tr>
          </thead>
          <tbody>
          <% @box_items.each do |item| %>
            <tr>
              <td><%= link_to item.title, item_path(item) %></td>
              <td><%= item.tags_to_s %></td>
              <td><%= link_to 'Edit', edit_item_path(item) %> | <%= link_to '(delete)', item_path(item), :method => :delete, :confirm => "yousure?" %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>

</div>

app/views/boxes/edit_info.html.erb
<h1>Edit Collection</h1>

<%= form_for @box, :url => box_path(@box) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
<% end %>

app/views/boxes/gallery.xml.erb
<tiltviewergallery>
  <photos>
    <%= @box.user_items.each do |item| %>
      <% global_item = Item.where(:title => item.title).first %>
      <photo imageurl="<%= image_path(item.image) %>" linkurl="<%= item_path(global_item) %>">
      <title><%= item.title %></title>
      <description><![CDATA[
        <% @template.global_fields.each do |gf| %>
          <%= gf.humanize %>:<%= eval("item.#{gf}") %>
        <% end %>
        ]]>
      </description>
    </photo>
    <% end %>
  </photos>
</tiltviewergallery>

app/views/boxes/index.html.erb
<h1>Box#index</h1>
<p>Find me in app/views/box/index.html.erb</p>

app/views/boxes/my_boxes.html.erb
<h1>My Collections</h1>
<p><%= link_to "Create Collection", new_box_path %><p>

<table class="zebra-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
  <% current_user.boxes.each do |b| %>
    <tr>
      <td><%= link_to b.name, box_path(b) %></td>
      <td><%= b.category.name %></td>
      <td><%= link_to 'Edit', edit_box_path(b) %> | <%= link_to "Add an Item", new_item_path(:id => b.id) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/boxes/new.html.erb
<h2>New Collection</h2>
<%= render :partial => "form" %>

app/views/boxes/show.html.erb
<div class="container">
  <div class="content">
    <div class="page-header">
      <% if current_user.id == @box.user_id %>
      <div class="quick-actions">
        <%= link_to 'Edit Collection', edit_box_path(@box), :class => 'btn' %>
        <%= link_to 'Add Item', new_item_path(:id => @box.id), :class => 'btn info' %>
      </div>
      <% end %>
      <h1><%= @box.name %><small> by <%= @box.user.name %></small></h1>
    </div>
    <div class="row">
      <div class="span16" style="height:600px;">
        <div id="flashcontent"></div>
      </div>
    </div>
  </div>

</div> 
<%= content_for :javascripts do %>
  <%= javascript_include_tag 'swfobject' %>
  <script type="text/javascript">
		var fo = new SWFObject("/TiltViewer.swf", "viewer", "100%", "100%", "9.0.28", "#000000");			
		
		// TILTVIEWER CONFIGURATION OPTIONS
		// To use an option, uncomment it by removing the "//" at the start of the line
		// For a description of config options, go to: 
		// http://www.airtightinteractive.com/projects/tiltviewer/config_options.html
															
		//FLICKR GALLERY OPTIONS
		// To use images from Flickr, uncomment this block
		//fo.addVariable("useFlickr", "true");
		//fo.addVariable("user_id", "48508968@N00");
		//fo.addVariable("tags", "jump,smile");
		//fo.addVariable("tag_mode", "all");
		//fo.addVariable("showTakenByText", "true");			
		
		// XML GALLERY OPTIONS
		// To use local images defined in an XML document, use this block		
		fo.addVariable("useFlickr", "false");
    fo.addVariable("xmlURL", "<%= gallery_box_path(@box) %>");
		fo.addVariable("maxJPGSize","800");
		
		//GENERAL OPTIONS		
		fo.addVariable("useReloadButton", "false");
		fo.addVariable("columns", "5");
		fo.addVariable("rows", "5");
		//fo.addVariable("showFlipButton", "true");
		fo.addVariable("showLinkButton", "True");		
		fo.addVariable("linkLabel", "See More");
		fo.addVariable("frameColor", "0xAAAAAA");
		fo.addVariable("backColor", "0xDDDDDD");
		fo.addVariable("bkgndInnerColor", "0xFFC448");
		fo.addVariable("bkgndOuterColor", "0xFFC448");				
		//fo.addVariable("langGoFull", "Go Fullscreen");
		//fo.addVariable("langExitFull", "Exit Fullscreen");
		//fo.addVariable("langAbout", "About");				
		
		// END TILTVIEWER CONFIGURATION OPTIONS
		
		fo.addParam("allowFullScreen","true");
		fo.write("flashcontent");			
	</script>
<% end %>