config/routes.rb
PassionBox::Application.routes.draw do
  get "trade/index"

  root :to => "home#index"

  match 'users/apply_user' => 'users#change_role', :via => :post, :as => :change_to_user, :role => User::USER
  match 'users/apply_curator' => 'users#change_role', :via => :post, :as => :change_to_curator, :role => User::CURATOR
  match 'users/apply_admin' => 'users#change_role', :via => :post, :as => :change_to_admin, :role => User::ADMIN
  resources :users, :only => [ :show, :edit, :update ]

  match '/auth/:provider/callback' => 'sessions#create'
  match '/signin' => 'sessions#new', :as => :signin
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/auth/failure' => 'sessions#failure'
  
  resources :items
  resources :boxes do 
    member do
      get :gallery
      get :edit_info
    end
  end
  match 'boxes/my_boxes' => 'boxes#my_boxes', :via =>:get, :as => :my_boxes
  
  resources :categories
  resources :templates
  resources :trade

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PassionBox</title>
  <%= stylesheet_link_tag "twitbootstrap", "style", "application" %>
  <%= javascript_include_tag "application", "bootstrap-dropdown" %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body>
  <div class="container">

    <div class="topbar" id="topbar">
      <div class="topbar-inner">
        <div class="container">
          <h3><%= link_to image_tag('logo.png', :height => '35px'), root_path %></h3>
          <div class="pull-right">
            <ul class="nav">
              <% if current_user %>
              <li><%= link_to 'My Profile', user_path(current_user) %></li>
              <li class="dropdown" data-dropdown="dropdown">
                <a href="#" class="dropdown-toggle">My Collections</a>
                <ul class="dropdown-menu">
                  <% current_user.boxes.each do |box| %>
                    <li><%= link_to box.name, box %>
                  <% end %>
                  <li class="divider"></li>
                  <li><%= link_to 'New Collection', categories_path %></li>
                </ul>
              </li>
              <% if current_user.curator? %>
              <li><%= link_to 'Curator Stuff', templates_path %></li>
              <% end %>
              <% if current_user.admin? %>
              <li><%= link_to 'Admin Stuff', categories_path %></li>
              <% end %>
              <li><%= link_to 'Sign Out', signout_path %></li>
              <% else %>
              <li><%= link_to image_tag('twitter_signin.png'), "auth/twitter" %></li>
              <li><%= link_to image_tag('facebook_signin.png'), "auth/facebook" %></li>
              <% end %>
            </ul>
        </div>
        </div>
      </div>
    </div>

    <div id="content">
      <%= flash_helper %>
      <%= yield %>
    </div>
    
    <footer>
      <p>&copy; This Awesome Company 2011</p>
    </footer>
  </div>
  <%= yield :javascripts %>
  <script type="text/javascript">
    $('#topbar').dropdown();
  </script>
</body>
</html>